import os
import time
import random
from colorama import Style,Back,Fore
sb = Style.BRIGHT
sr = Style.RESET_ALL
blm = Back.LIGHTMAGENTA_EX
blb = Back.LIGHTBLUE_EX
lr = Fore.LIGHTRED_EX
blr = Back.LIGHTRED_EX
lw = Fore.LIGHTWHITE_EX
blg = Back.LIGHTGREEN_EX

def animacionCargaAplicacion():
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'"Iniciando Gestor De Tareas"':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩                      |               |")
    print(f"|              |🟩                      |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.5)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'Cargando aplicación':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩                    |               |")
    print(f"|              |🟩🟩                    |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.3)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'Cargando aplicación':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩                  |               |")
    print(f"|              |🟩🟩🟩                  |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.8)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'Cargando aplicación':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩🟩                |               |")
    print(f"|              |🟩🟩🟩🟩                |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.1)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'Cargando datos':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩🟩🟩              |               |")
    print(f"|              |🟩🟩🟩🟩🟩              |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.3)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'"Iniciando el Panel Principal"':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩🟩🟩🟩            |               |")
    print(f"|              |🟩🟩🟩🟩🟩🟩            |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(1)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'"Iniciando el Panel Principal"':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩          |               |")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩          |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.3)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'"Iniciando el Panel Principal"':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩        |               |")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩        |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.3)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'"Iniciando el Panel Principal"':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩🟩      |               |")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩🟩      |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.3)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'"Iniciando el Panel Principal"':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩    |               |")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩    |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.3)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'"Iniciando el Panel Principal"':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩  |               |")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩  |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(1)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'"Iniciando ..."':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩|               |")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩|               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.3)
    
# ************************************ Animaciones de Carga *********************************************
# *******************************************************************************************************

def animacionDeCarga(mensaje:str,caracter:str):
    # Esta funcion 
    veces = random.randint(1,2)

    for v in range(veces):
        print(f"\r{mensaje}",end="")
        for c in range(4):
            print(f"{caracter}",end="",flush=True)
            time.sleep(0.3)
        print("\r                                           ",end="")

# *************************************** Barra de carga ************************************************
# *******************************************************************************************************

def barraDeCarga():
    carga = 0
    cargaTotal = 10
    print()
    for _ in range(cargaTotal+1):
        barra:str = f"{sb}Cargando {lw}|{sr}"

        for _ in range(carga):
            barra += f"{blg}       {sr}"

        espacios = cargaTotal-carga

        for _ in range(espacios):
            barra += "       "

        barra += f"{sb}{lw}|{sr} "
        carga += 1
        print(f"\r{barra}",flush=True, end="")
        velocidad = random.uniform(0.01,0.3)
        time.sleep(velocidad)

