import os
import time
import random
from colorama import Style
sb = Style.BRIGHT
sr = Style.RESET_ALL

def animacionCargaAplicacion():
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'"Iniciando Gestor De Tareas"':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩                      |               |")
    print(f"|              |🟩                      |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(2)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'Cargando aplicación':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩                    |               |")
    print(f"|              |🟩🟩                    |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.3)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'Cargando aplicación':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩                  |               |")
    print(f"|              |🟩🟩🟩                  |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.8)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'Cargando aplicación':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩🟩                |               |")
    print(f"|              |🟩🟩🟩🟩                |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.1)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'Cargando datos':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩🟩🟩              |               |")
    print(f"|              |🟩🟩🟩🟩🟩              |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{'Y':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.3)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'"Iniciando el Panel Principal"':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩🟩🟩🟩            |               |")
    print(f"|              |🟩🟩🟩🟩🟩🟩            |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{'Y':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(1.5)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'"Iniciando el Panel Principal"':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩          |               |")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩          |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{'Y':^55}|")
    print(f"|{sb}{'Johanny Sánchez':^55}{sr}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.3)
    #sdfsdfasdfas
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'"Iniciando el Panel Principal"':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩        |               |")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩        |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{'Y':^55}|")
    print(f"|{sb}{'Johanny Sánchez':^55}{sr}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.3)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'"Iniciando el Panel Principal"':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩🟩      |               |")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩🟩      |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{'Y':^55}|")
    print(f"|{sb}{'Johanny Sánchez':^55}{sr}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.3)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'"Iniciando el Panel Principal"':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩    |               |")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩    |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{'Y':^55}|")
    print(f"|{sb}{'Johanny Sánchez':^55}{sr}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.3)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'"Iniciando el Panel Principal"':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩  |               |")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩  |               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{'Y':^55}|")
    print(f"|{sb}{'Johanny Sánchez':^55}{sr}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(2)
    os.system("clear")
    print("---------------------------------------------------------")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{'"Iniciando ..."':^55}|")
    print(f"|{' ':^55}|")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩|               |")
    print(f"|              |🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩|               |")
    print(f"|{' ':^55}|")
    print(f"|{'Creado por:':^55}|")
    print(f"|{' ':^55}|")
    print(f"|{sb}{'Frank Camarena':^55}|{sr}")
    print(f"|{'Y':^55}|")
    print(f"|{sb}{'Johanny Sánchez':^55}{sr}|")
    print(f"|{' ':^55}|")
    print(f"|{' ':^55}|")
    print("---------------------------------------------------------")
    time.sleep(0.3)
    
# ************************************ Animaciones de Carga *********************************************
# *******************************************************************************************************

def animacionPuntos():
    veces = random.randint(1,2)

    for v in range(veces):
        print("\rCargando",end="")
        for punto in range(5):
            print(".",end="",flush=True)
            time.sleep(0.2)
        print("\r                   ",end="")

#********************************************************************************************************

def animacionAgregandoTarea():
    veces = random.randint(1,2)

    for v in range(veces):
        print("\rAgregando la tarea",end="")
        for punto in range(5):
            print(".",end="",flush=True)
            time.sleep(0.2)
        print("\r                            ",end="")